# Generated by Django 3.0.2 on 2020-01-26 00:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('webSupport', models.BooleanField()),
                ('shape', models.CharField(choices=[('oval', 'Oval'), ('rectangular', 'Rectangular'), ('canopy', 'Canopy'), ('elevated', 'Elevated')], max_length=50)),
                ('createdOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedOn', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('doj', models.DateField()),
                ('standard', models.IntegerField()),
                ('rollNo', models.IntegerField()),
                ('ranking', models.IntegerField()),
                ('createdOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedOn', models.DateTimeField(auto_now=True)),
                ('classes', models.ManyToManyField(to='classroom.ClassRoom')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('perClassDuration', models.IntegerField(validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(30)])),
                ('totalDuration', models.IntegerField()),
                ('createdOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedOn', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('doj', models.DateField()),
                ('webSupport', models.BooleanField()),
                ('annualSalary', models.FloatField()),
                ('createdOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedOn', models.DateTimeField(auto_now=True)),
                ('subjects', models.ManyToManyField(to='classroom.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='StudentContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactName', models.CharField(max_length=200)),
                ('contactNumber', models.CharField(max_length=200)),
                ('relation', models.CharField(max_length=200)),
                ('createdOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedOn', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.Student')),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedOn', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.ClassRoom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classroom.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classroom.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='subjects',
            field=models.ManyToManyField(through='classroom.ClassroomSubject', to='classroom.Subject'),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('order', models.IntegerField()),
                ('createdOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedOn', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classroom.Subject')),
            ],
        ),
    ]
